-- Seed a small Property policy book (S001). FROZEN once loaded.

INSERT INTO GC_CUST (CUSTNO, CUSTNM, CTRYCD, CURRCD) VALUES ('CUST0001', 'Durand SARL', 'FR', 'EUR');
INSERT INTO GC_CUST (CUSTNO, CUSTNM, CTRYCD, CURRCD) VALUES ('CUST0002', 'Boulangerie Lemoine', 'FR', 'EUR');

INSERT INTO GC_POLICY (POLNO, CUSTNO, LOBCD, STATCD, EFFDT, EXPDT, SUMINS)
  VALUES ('POLPROP001', 'CUST0001', 'PRO', 'A', DATE '2026-01-01', DATE '2026-12-31', 500000);
INSERT INTO GC_POLICY (POLNO, CUSTNO, LOBCD, STATCD, EFFDT, EXPDT, SUMINS)
  VALUES ('POLPROP002', 'CUST0002', 'PRO', 'A', DATE '2026-03-01', DATE '2027-02-28', 250000);

INSERT INTO GC_POLPRL (POLNO, PRLCD) VALUES ('POLPROP001', 'FIRE');
INSERT INTO GC_POLPRL (POLNO, PRLCD) VALUES ('POLPROP001', 'WATR');
INSERT INTO GC_POLPRL (POLNO, PRLCD) VALUES ('POLPROP001', 'STRM');
INSERT INTO GC_POLPRL (POLNO, PRLCD) VALUES ('POLPROP001', 'THFT');
INSERT INTO GC_POLPRL (POLNO, PRLCD) VALUES ('POLPROP002', 'FIRE');
INSERT INTO GC_POLPRL (POLNO, PRLCD) VALUES ('POLPROP002', 'WATR');

COMMIT;
